#
# Author:: Fletcher Nichol (<fnichol@nichol.ca>)
#
# Copyright (C) 2013, Fletcher Nichol
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "busser/thor"
require "busser/plugin"

module Busser

  module Command

    # Setup command.
    #
    # @author Fletcher Nichol <fnichol@nichol.ca>
    #
    class Setup < Busser::Thor::BaseGroup

      class_option :type,
        desc: "Type of binstub file to create (bourne or bat)",
        default: "bourne"

      # Creates the Busser root and the binstub that runs Busser with an
      # isolated gem environment.
      #
      # @return [void]
      def perform
        banner "Setting up Busser"
        create_busser_root
        generate_busser_binstub
      end

      private

      # @return [void]
      def create_busser_root
        info "Creating BUSSER_ROOT in #{root_path}"
        empty_directory(root_path, verbose: false)
      end

      # Writes the binstub, in whichever flavour --type asked for.
      #
      # @return [void]
      def generate_busser_binstub
        info "Creating busser binstub"

        if options[:type] == "bat"
          generate_busser_binstub_for_bat
        else
          generate_busser_binstub_for_bourne
        end
      end

      # Writes a Windows batch binstub.
      #
      # @return [void]
      def generate_busser_binstub_for_bat
        binstub = root_path + "bin/busser.bat"
        busser_root = root_path.to_s.gsub("/", "\\")

        File.unlink(binstub) if File.exist?(binstub)
        create_file(binstub, verbose: false) do
          <<-BUSSER_BINSTUB.gsub(/^ {12}/, "")
            @ECHO OFF
            REM This file was generated by Busser.
            REM
            REM The application 'busser' is installed as part of a gem, and
            REM this file is here to facilitate running it.

            REM Make sure any variables we set exist only for this batch file
            SETLOCAL

            REM Set Busser Root Path
            SET "BUSSER_ROOT=#{busser_root}"

            REM Export gem paths so that we use the isolated gems.
            SET "GEM_HOME=#{gem_home}"
            SET "GEM_PATH=#{gem_path}"
            SET "GEM_CACHE=#{gem_home}\\cache"

            REM Keep the calling Ruby environment out of this one. Clearing
            REM RUBYOPT is no longer enough: RubyGems requires bundler/setup
            REM whenever BUNDLER_SETUP is set, and bundler then points GEM_HOME
            REM at the calling project's bundle, undoing the isolation above.
            SET RUBYOPT=
            SET GEMRC=
            SET RUBYLIB=
            SET BUNDLER_SETUP=
            SET BUNDLER_VERSION=
            SET BUNDLE_BIN_PATH=
            SET BUNDLE_GEMFILE=
            SET BUNDLE_LOCKFILE=
            SET BUNDLE_PATH=

            REM Call the actual Busser bin with our arguments
            "#{ruby_bin}" "#{gem_bindir}\\busser" %*

            REM Store the exit status so we can re-use it later
            SET "BUSSER_EXIT_STATUS=%ERRORLEVEL%"

            REM Exit with the proper exit status from Busser
            exit /b %BUSSER_EXIT_STATUS%
          BUSSER_BINSTUB
        end
      end

      # Writes a Bourne shell binstub, executable.
      #
      # @return [void]
      def generate_busser_binstub_for_bourne
        binstub = root_path + "bin/busser"

        File.unlink(binstub) if File.exist?(binstub)
        create_file(binstub, verbose: false) do
          <<-BUSSER_BINSTUB.gsub(/^ {12}/, "")
            #!/usr/bin/env sh
            #
            # This file was generated by Busser.
            #
            # The application 'busser' is installed as part of a gem, and
            # this file is here to facilitate running it.
            #
            if test -n "$DEBUG"; then set -x; fi

            # Set Busser Root path
            BUSSER_ROOT="#{root_path}"

            export BUSSER_ROOT

            # Export gem paths so that we use the isolated gems.
            GEM_HOME="#{gem_home}"; export GEM_HOME
            GEM_PATH="#{gem_path}"; export GEM_PATH
            GEM_CACHE="#{gem_home}/cache"; export GEM_CACHE

            # Keep the calling Ruby environment out of this one. Unsetting
            # RUBYOPT is no longer enough: RubyGems requires bundler/setup
            # whenever BUNDLER_SETUP is set, and bundler then points GEM_HOME
            # at the calling project's bundle, undoing the isolation above.
            unset RUBYOPT GEMRC RUBYLIB BUNDLER_SETUP BUNDLER_VERSION
            unset BUNDLE_BIN_PATH BUNDLE_GEMFILE BUNDLE_LOCKFILE BUNDLE_PATH

            # Call the actual Busser bin with our arguments
            exec "#{ruby_bin}" "#{gem_bindir}/busser" "$@"
          BUSSER_BINSTUB
        end
        chmod(binstub, 0755, verbose: false)
      end

      # @return [String] path to the Ruby that is running Busser, in the path
      #   style the target binstub needs
      def ruby_bin
        result = if (bindir = RbConfig::CONFIG["bindir"])
                   File.join(bindir, "ruby")
                 else
                   "ruby"
                 end
        result = result.gsub("/", "\\").concat(".exe") if bat?
        result
      end

      # @return [String] the isolated gem home the binstub exports
      def gem_home
        Gem.paths.home.dup.tap { |p| p.gsub!("/", "\\") if bat? }
      end

      # The separator differs by platform, and the bat binstub is generated on
      # and for Windows, where RubyGems splits GEM_PATH on ";". Joining with
      # ":" there produced one unusable entry -- every Windows path already
      # contains a colon after its drive letter -- so the isolated gem
      # environment the binstub exists to create silently did not exist.
      #
      # @return [String] the gem path the binstub exports
      def gem_path
        Gem.paths.path.join(bat? ? ";" : ":").dup.tap { |p| p.gsub!("/", "\\") if bat? }
      end

      # @return [String] directory holding the real busser executable
      def gem_bindir
        Gem.bindir.dup.tap { |p| p.gsub!("/", "\\") if bat? }
      end

      # @return [Boolean] true when generating a Windows batch binstub
      def bat?
        options[:type] == "bat"
      end
    end
  end
end
