Feature: Setup command
  In order to make Busser self-reliant with little external initialization
  As a user of Busser
  I want a command to set up Busser's environment

  Background:
    Given a test BUSSER_ROOT directory named "busser-setup"
    And I delete the BUSSER_ROOT directory

  Scenario: Busser home is set up
    Given I run `busser setup`
    Then the BUSSER_ROOT directory should exist
    And a busser binstub file should contain:
    """
    This file was generated by Busser.
    """
    And the exit status should be 0
